// Translate playbooks into HyperFrames-friendly style artifacts.

export const FALLBACK_CSS_VARS: Record<string, string> = {
  "--color-bg": "#0B0F1A",
  "--color-fg": "#F5F5F5",
  "--color-accent": "#F59E0B",
  "--color-primary": "#2563EB",
  "--color-secondary": "#10B981",
  "--color-surface": "#111827",
  "--color-muted": "#6B7280",
  "--font-heading": "Inter",
  "--font-body": "Inter",
  "--font-mono": "JetBrains Mono",
  "--ease-primary": "cubic-bezier(0.65, 0, 0.35, 1)",
  "--ease-entrance": "cubic-bezier(0.33, 1, 0.68, 1)",
  "--ease-exit": "cubic-bezier(0.32, 0, 0.67, 0)",
  "--duration-entrance": "0.6s",
  "--duration-transition": "0.5s",
};

function first(raw: any, defaultValue: string): string {
  if (Array.isArray(raw) && raw.length) return String(raw[0]);
  if (typeof raw === "string" && raw) return raw;
  return defaultValue;
}

function font(typo: Record<string, any>, key: string, defaultValue: string): string {
  const node = typo[key] ?? {};
  if (node && typeof node === "object" && !Array.isArray(node)) {
    return String(node.font ?? node.family ?? defaultValue);
  }
  if (typeof node === "string") return node;
  return defaultValue;
}

function motionEasing(motion: Record<string, any>): [string, string] {
  const pace = String(motion.pace ?? "moderate").toLowerCase();
  if (pace === "fast") return ["0.4s", "cubic-bezier(0.33, 1, 0.68, 1)"];
  if (pace === "slow") return ["0.9s", "cubic-bezier(0.65, 0, 0.35, 1)"];
  return ["0.6s", "cubic-bezier(0.5, 0, 0.5, 1)"];
}

export function styleBridge(
  playbook: Record<string, any> | null,
  editDecisions: Record<string, any> | null = null,
): [Record<string, string>, string] {
  const css: Record<string, string> = { ...FALLBACK_CSS_VARS };
  let sourceNote = "built-in fallback palette";
  let playbookName = "";

  if (playbook) {
    playbookName = String(playbook.name ?? playbook.id ?? playbook.display_name ?? "");
    const vl = playbook.visual_language ?? {};
    const palette = vl.color_palette ?? {};
    const typo = playbook.typography ?? {};
    const motion = playbook.motion ?? {};

    const bg = first(palette.background, css["--color-bg"] as string);
    const fg = first(palette.text, css["--color-fg"] as string);
    const accent = first(palette.accent, css["--color-accent"] as string);
    const primary = first(palette.primary, css["--color-primary"] as string);
    const secondary = first(palette.secondary, css["--color-secondary"] as string);
    const surface = first(palette.surface, css["--color-surface"] as string);
    const muted = first(palette.muted_text, css["--color-muted"] as string);
    const [duration, ease] = motionEasing(motion);

    css["--color-bg"] = bg;
    css["--color-fg"] = fg;
    css["--color-accent"] = accent;
    css["--color-primary"] = primary;
    css["--color-secondary"] = secondary;
    css["--color-surface"] = surface;
    css["--color-muted"] = muted;
    css["--font-heading"] = font(typo, "heading", css["--font-heading"] as string);
    css["--font-body"] = font(typo, "body", css["--font-body"] as string);
    css["--font-mono"] = font(typo, "code", css["--font-mono"] as string);
    css["--ease-primary"] = ease;
    css["--duration-entrance"] = duration;

    sourceNote = playbookName ? `playbook \`${playbookName}\`` : "loaded playbook";
  }

  if (editDecisions) {
    const meta = editDecisions.metadata ?? {};
    if (meta.primary_color) css["--color-primary"] = String(meta.primary_color);
    if (meta.accent_color) css["--color-accent"] = String(meta.accent_color);
    if (meta.background_color) css["--color-bg"] = String(meta.background_color);
    if (meta.text_color) css["--color-fg"] = String(meta.text_color);
  }

  return [css, renderDesignMd(css, sourceNote, playbookName)];
}

export function renderDesignMd(css: Record<string, string>, sourceNote: string, playbookName: string): string {
  const title = playbookName ? `# DESIGN - ${playbookName}` : "# DESIGN";
  const lines = [
    title,
    "",
    `> Generated by Montara HyperFrames style bridge (source: ${sourceNote}).`,
    "",
    "## Colors",
    "",
    `- Background: \`${css["--color-bg"]}\``,
    `- Foreground: \`${css["--color-fg"]}\``,
    `- Primary: \`${css["--color-primary"]}\``,
    `- Accent: \`${css["--color-accent"]}\``,
    `- Secondary: \`${css["--color-secondary"]}\``,
    `- Surface: \`${css["--color-surface"]}\``,
    `- Muted text: \`${css["--color-muted"]}\``,
    "",
    "## Typography",
    "",
    `- Heading: \`${css["--font-heading"]}\``,
    `- Body: \`${css["--font-body"]}\``,
    `- Mono: \`${css["--font-mono"]}\``,
    "",
    "## Motion",
    "",
    `- Primary ease: \`${css["--ease-primary"]}\``,
    `- Entrance duration: \`${css["--duration-entrance"]}\``,
    "",
    "## How to use in compositions",
    "",
    "Reference these tokens via `var(...)` instead of hard-coding hex",
    "values or font names:",
    "",
    "```css",
    ".scene-content h1 {",
    "  font-family: var(--font-heading);",
    "  color: var(--color-fg);",
    "}",
    ".scene-content .accent {",
    "  color: var(--color-accent);",
    "}",
    "```",
    "",
    "When adjusting a composition's look, edit the `:root` block in",
    "`index.html` (or this bridge for cross-project changes), not the",
    "individual scene styles.",
    "",
  ];
  return lines.join("\n");
}
